CREATE TABLE "GCG_4826_SO_WIPTOFG"(
 "ORDER_NO" CHAR(7),
 "RECORD_NO" CHAR(4),
 "PART" CHAR(20),
 "PRODUCT_LINE" CHAR(2),
 "DESCRIPTION" CHAR(30),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "QTY_ORDERED" DOUBLE,
 "QTY_SCANNED" DOUBLE,
 "TO_BIN" CHAR(6),
 "WIPTOFG" CHAR(1),
 "WIP_QTY" DOUBLE,
 "DEFAULT_BIN" CHAR(6),
 "INV_QTY" DOUBLE,
 "COMMENT" CHAR(30));

CREATE UNIQUE NOT MODIFIABLE INDEX "GCG_4826_SO_WIPTOFG" USING 0 ON "GCG_4826_SO_WIPTOFG"("ORDER_NO", "RECORD_NO");